CREATE TABLE PROPERTIES(
    UUID BINARY(16) NOT NULL,
    ADDRESS VARCHAR(1024) NOT NULL,
    SUBDISTRICT VARCHAR(128) NOT NULL,
    TYPE VARCHAR(32) NOT NULL,
    AREA DOUBLE(10,2) NOT NULL,
    BEDS INTEGER NOT NULL DEFAULT 0,
    HALLS INTEGER NOT NULL DEFAULT 0,
    BATHS INTEGER NOT NULL DEFAULT 0,
    PRICE DOUBLE(10,2) NOT NULL,
    CREATED_AT TIMESTAMP (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    AVAILABLE_AT TIMESTAMP (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CREATED_BY BINARY(16) NOT NULL
)ENGINE=InnoDB CHARACTER SET=utf8;
